### ISSUE TITLE
MAC calculation for Aktia with test credentials fails

### ISSUE THREAD

**Issue by jussikinnula** [reaktor/node-tupas#10]
With Aktia & test credentials, MAC calculations fails:

Test credentials:
https://github.com/reaktor/node-tupas/blob/master/config.json#L56-L67

The function producing non-matching MAC:
https://github.com/reaktor/node-tupas/blob/master/tupas.js#L219-L222

**Comment by jussikinnula** [comment]
More specifically, this happens when coming back from Tupas to "success" URL, with the following code:

`function ok(req, res) {
    if (req.query.B02K_MAC && req.query.B02K_MAC.toUpperCase() === tupas.responseMac(request.query)) {
        res.send({ message: 'OK' });
    } else {
        res.send({ message: 'FAIL' });
    }
}`

**Comment by Dolmio** [comment]
I was able to reproduce this and #9 with the sample app. The tests are failing for me after clean clone and with node 6. Something to do with the casperjs versions. The tests passed for my colleague who tested this quickly yesterday, so I guess it's some kind of version issue. I will investigate this further. Thanks for reporting and sorry for the late reply!
