### ISSUE TITLE
Insecure example requestId

### ISSUE THREAD

**Issue by hsintonen** [reaktor/node-tupas#15]
http://www.finanssiala.fi/maksujenvalitys/dokumentit/Tupas-varmennepalvelu_v23c.pdf
"Kenttä 5 Palveluntarjoajan tunnistuspyynnölle antama yksilöivä tunnus. Tunnuksena voi olla viite, asiakasnumero tai yhdistelmä päivämäärästä, kellonajasta ja juoksevasta tunnuksesta sekä viitteestä."

If using the last digits "123456" as in [sample/app.js](https://github.com/reaktor/node-tupas/blob/98ab64617a6692a28577b658bdd947ac20d50900/sample/app.js#L47) results in a problem where two or more authentications occurring within the same second cannot be distinguished. Depending on the implementation this can lead to the application using wrong identity.

As such I think the example is a bit dangerous. It should rather use current time microseconds or possibly a globally running counter % 1000000.

**Comment by Dolmio** [comment]
Thx, for pointing that out. I updated the sample app in bfe8ee06f9c4312df6536891dad395e611b200ac.
