### ISSUE TITLE
MAC calculation for S-pankki with test credentials fails

### ISSUE THREAD

**Issue by jussikinnula** [reaktor/node-tupas#9]
With S-pankki & test credentials, MAC calculations fails:

Test credentials:
https://github.com/reaktor/node-tupas/blob/master/config.json#L82-L93

The function producing non-matching MAC:
https://github.com/reaktor/node-tupas/blob/master/tupas.js#L219-L222

**Comment by jussikinnula** [comment]
More specifically, this happens when coming back from Tupas to "success" URL, with the following code:

`function ok(req, res) {
  if (req.query.B02K_MAC && req.query.B02K_MAC.toUpperCase() === tupas.responseMac(request.query)) {
    res.send({ message: 'OK' });
  } else {
    res.send({ message: 'FAIL' });
  }
}`

**Comment by Dolmio** [comment]
#11 fixes this
